 name: Deploy

on:
  push:
    branches:
      - main  # Change if you're using a different default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'  # Fetches the full Git history

      - name: Install Dependencies
        run: npm install

      - name: Run Elocuent
        run: |
          npx elocuent -d . -o meta/loc.csv

      - name: Commit and Push Updated loc.csv
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          mkdir -p meta
          git pull
          git add -f meta/loc.csv
          git commit -m "Update code statistics" || echo "No changes to commit"
          git push
          
    permissions:
      contents: write
      pages: write
      id-token: write
